package com.eugene.cafe.controller.command;

public enum CommandType {

    LOG_IN,
    LOG_OUT,
    DEFAULT,
    GO_TO_FORGOT_PASSWORD_PAGE,
    GO_TO_SIGNUP_PAGE,
    SIGN_UP,
    CHANGE_LOCALE,
    GO_TO_PROFILE_SETTINGS_PAGE,
    EDIT_USER_PROFILE,
    UPDATE_PROFILE_PICTURE,
    CHANGE_PASSWORD,
    GO_TO_ADMIN_DASHBOARD_PAGE,
    ADD_MENU_ITEM,
    GO_TO_MAIN_PAGE,
    GO_TO_MENU_PAGE,
    CHANGE_SORT_ORDER,
    CHANGE_CURRENT_CATEGORY
}
